### ISSUE TITLE
Increase Replicas of Deployment

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/devhub-signing-web#55]
there is only 1 replica being created for this application, it wouldn't be resilient to a node evac or failure. 

<img width="1346" alt="Screen Shot 2019-06-04 at 9 00 15 AM" src="https://user-images.githubusercontent.com/21046727/58894641-34806180-86a7-11e9-8dc3-28d5757c37ef.png">

**Comment by jleach** [comment]
Moved to new repo.
